name: HoeCraft
version: 1.1
author: Razi
main: fr.razi.houe.Main
commands:
  givehoue:
    description: This command give you a hoe that harve and replant in a 5 block radius
    permission: givehoue.use
